apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  template:
    metadata:
      name: web-app-pod
      labels:
        app: web
    spec:
      containers:
        - image: ahmedmorsi/project
          name: container-name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80